// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    DarkModeToggle: typeof import('./src/components/DarkModeToggle.vue')['default']
    DynamicLayout: typeof import('./src/components/DynamicLayout.vue')['default']
    LayoutsDefault: typeof import('./src/components/layouts/default.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ServiceWorkerPrompt: typeof import('./src/components/ServiceWorkerPrompt.vue')['default']
    UiAccordion: typeof import('./src/components/ui/Accordion/index.vue')['default']
    UiAccordionItem: typeof import('./src/components/ui/Accordion/item.vue')['default']
    UiButton: typeof import('./src/components/ui/Button.vue')['default']
    UiCenter: typeof import('./src/components/ui/Center.vue')['default']
    UiConfirmableDatePicker: typeof import('./src/components/ui/ConfirmableDatePicker.vue')['default']
    UiContainer: typeof import('./src/components/ui/Container.vue')['default']
    UiDatePicker: typeof import('./src/components/ui/DatePicker/index.vue')['default']
    UiDatePickerCalendarView: typeof import('./src/components/ui/DatePicker/CalendarView.vue')['default']
    UiDatePickerMonthView: typeof import('./src/components/ui/DatePicker/MonthView.vue')['default']
    UiDatePickerTime: typeof import('./src/components/ui/DatePicker/Time.vue')['default']
    UiDatePickerYearView: typeof import('./src/components/ui/DatePicker/YearView.vue')['default']
    UiDrawer: typeof import('./src/components/ui/Drawer.vue')['default']
    UiDropdown: typeof import('./src/components/ui/Dropdown/index.vue')['default']
    UiDropdownItem: typeof import('./src/components/ui/Dropdown/Item.vue')['default']
    UiFormControl: typeof import('./src/components/ui/Form/Control.vue')['default']
    UiFormError: typeof import('./src/components/ui/Form/Error.vue')['default']
    UiFormLabel: typeof import('./src/components/ui/Form/Label.vue')['default']
    UiIconButton: typeof import('./src/components/ui/IconButton.vue')['default']
    UiInputAutoComplete: typeof import('./src/components/ui/Input/AutoComplete.vue')['default']
    UiInputCheckbox: typeof import('./src/components/ui/Input/Checkbox.vue')['default']
    UiInputPassword: typeof import('./src/components/ui/Input/Password.vue')['default']
    UiInputRadio: typeof import('./src/components/ui/Input/Radio.vue')['default']
    UiInputSelect: typeof import('./src/components/ui/Input/Select.vue')['default']
    UiInputSwitch: typeof import('./src/components/ui/Input/Switch.vue')['default']
    UiInputText: typeof import('./src/components/ui/Input/Text.vue')['default']
    UiLink: typeof import('./src/components/ui/Link.vue')['default']
    UiModal: typeof import('./src/components/ui/Modal.vue')['default']
    UiSpinner: typeof import('./src/components/ui/Spinner.vue')['default']
    UiSurface: typeof import('./src/components/ui/Surface.vue')['default']
    UiToast: typeof import('./src/components/ui/Toast/index.vue')['default']
    UiToastBar: typeof import('./src/components/ui/Toast/Bar.vue')['default']
    UserAvatar: typeof import('./src/components/user/Avatar.vue')['default']
  }
}
